### ISSUE TITLE
Can't wrap NP_Buffer in struct

### ISSUE THREAD

**Issue by SoMuchSpace** [only-cliches/NoProto#13]
Hello!
I found weird bug. I tried to wrap NP_Buffer in struct like this:
```Rust
use no_proto::{NP_Factory, buffer::NP_Buffer, error::NP_Error, memory::NP_Memory_Owned};

struct Test {
    buffer: NP_Buffer<NP_Memory_Owned>
}

impl Test {
    fn new(field: i64) -> Result<Self, NP_Error> {
        let factory = NP_Factory::new(r#"
            struct({fields: {
                field: i64()
            }})
        "#)?;
        let mut test = Self {
            buffer: factory.new_buffer(None)
        };
        test.set_field(field)?;
        Ok(test)
    }

    fn get_field(&self) -> Result<Option<i64>, NP_Error> {
        self.buffer.get::<i64>(&["field"])
    }

    fn set_field(&mut self, field: i64) -> Result<bool, NP_Error> {
        self.buffer.set(&["field"], field)
    }
}

fn main() -> Result<(), NP_Error> {
    let test = Test::new(0)?;
    assert_eq!(test.get_field()?, Some(0));
    Ok(())
}
```
On Windows 10 this code:
* sometimes works
* sometimes `test.get_field()` returns `Ok(None)`
* sometimes crashes with
`error: process didn't exit successfully: 'target\debug\np_test.exe' (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)`

On Ubuntu (WLS) this code always crashes with
`Segmentation fault (core dumped)`

Without struct everything work fine.

**Comment by SoMuchSpace** [comment]
Found the problem - NP_Buffer doesn't work when NP_Factory is destroyed.
It would be nice to have proper error message (or even better - compile error), but it works now.

**Comment by only-cliches** [comment]
Yes,'NP_Buffer' should never exist absent an `NP_Factory`, since the buffer must use a schema, and the schema can only come from a factory.

Could you make some suggestions for the docs that would have helped you in this situation?
